import React, { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, CircleHelp, Play, RefreshCw } from 'lucide-react';

type Json=Record<string,any>;
const btn='inline-flex items-center gap-2 rounded-lg border border-[#2b4b7a] bg-[#182a44] px-3 py-2 text-xs font-semibold text-[#89ceff] transition hover:bg-[#233d64] disabled:cursor-not-allowed disabled:opacity-50';
async function request<T=Json>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{'Content-Type':'application/json',...init?.headers}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||`${r.status} ${r.statusText}`);return data as T;}
function Panel({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-xl border border-[#1e2f4d] bg-[#0e172a] p-4"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-white">{title}</h2>{action}</div>{children}</section>;}

export default function Experiment9Panel(){
  const [runtime,setRuntime]=useState<Json|null>(null);const [latest,setLatest]=useState<Json|null>(null);const [events,setEvents]=useState<Json[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{const state=await request('/api/experiments/9/status');setRuntime(state);const [runLog,eventLog]=await Promise.all([request('/api/experiments/9/results').catch(()=>null),request<Json[]>('/api/experiments/9/events').catch(()=>[])]);setLatest(runLog);setEvents(eventLog);return state;},[]);
  useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:String(e)));},[refresh]);
  const execute=async()=>{setBusy(true);setError('');try{const result=await request('/api/experiments/9/run',{method:'POST'});setLatest({runId:result.runId,status:result.status,startedAt:result.startedAt,completedAt:result.completedAt,summary:{results:result.results,stdout:result.stdout,stderr:result.stderr,command:result.command,durationMillis:result.durationMillis},error:result.error});setEvents(await request<Json[]>('/api/experiments/9/events'));if(result.status!=='SUCCEEDED')setError(result.error||'MPI process failed; inspect captured output below.');}catch(e){setError(e instanceof Error?e.message:String(e));const [runLog,eventLog]=await Promise.all([request('/api/experiments/9/results').catch(()=>null),request<Json[]>('/api/experiments/9/events').catch(()=>[])]);setLatest(runLog);setEvents(eventLog);}finally{setBusy(false);}};
  const results:Json=latest?.summary?.results??{};const okay=latest?.status==='SUCCEEDED';
  const ranks=[0,1,2,3];const scatter:number[]=Array.isArray(results.scatter)?results.scatter:[];const gathered:number[]=Array.isArray(results.gather)?results.gather:[];
  const box='rounded-lg border border-[#1e2f4d] bg-[#091122] p-3';
  return <div className="space-y-4">
    <Panel title="MPI runtime and execution" action={<button className={btn} disabled={busy} onClick={()=>void refresh().catch(e=>setError(String(e)))}><RefreshCw className="h-3 w-3"/>Refresh</button>}>
      <p className="text-xs text-[#8299b8]">Broadcast · Scatter · Gather. This page invokes a four-process MPJ Express job through Docker; the backend captures its process output and saves every run in PostgreSQL.</p>
      {error&&<div role="alert" className="mt-3 rounded-lg border border-rose-800 bg-rose-950/40 p-3 text-xs text-rose-200"><AlertTriangle className="mr-2 inline h-4 w-4"/>{error}</div>}
      <div className="mt-3 grid gap-2 sm:grid-cols-5"><Metric label="MPI status" value={runtime?.configured?'READY':'NOT CONFIGURED'}/><Metric label="Runtime" value={runtime?.runtime??'Checking…'}/><Metric label="Ranks" value={runtime?.ranks??'—'}/><Metric label="Root" value={`Rank ${runtime?.rootRank??0}`}/><Metric label="Last run" value={latest?.status??'No run yet'}/></div>
      {runtime?.message&&<p className={`mt-2 text-[11px] ${runtime.configured?'text-emerald-300':'text-amber-200'}`}>{runtime.message}</p>}
      <button className={`${btn} mt-3`} disabled={busy||!runtime?.configured} onClick={()=>void execute()}><Play className="h-3 w-3"/>{busy?'Running four MPI ranks…':'Run complete experiment'}</button>
      {latest?.summary?.durationMillis!=null&&<span className="ml-3 text-[11px] text-[#8299b8]">Execution {latest.summary.durationMillis} ms · run #{latest.runId}</span>}
    </Panel>
    <Panel title="Four MPI ranks · communicator">
      <div className="mx-auto max-w-sm rounded-lg border border-cyan-800/70 bg-cyan-950/20 p-3 text-center"><div className="text-[10px] font-bold tracking-widest text-cyan-300">ROOT · RANK 0</div><div className="mt-1 text-xs text-white">{results.broadcast??'Broadcast value appears after execution'}</div></div>
      <div className="my-2 flex justify-center text-lg text-[#89ceff]">↓ Broadcast · one value copied to every rank</div>
      <div className="grid gap-2 sm:grid-cols-4">{ranks.map(rank=><div key={rank} className={`${box} text-center`}><div className="text-xs font-bold text-white">Rank {rank}{rank===0?' · ROOT':''}</div><div className="mt-2 text-[10px] text-[#8299b8]">Received same job type</div><div className="mt-1 text-xs font-semibold text-cyan-200">{results.broadcast??'—'}</div></div>)}</div>
    </Panel>
    <div className="grid gap-4 xl:grid-cols-2">
      <Panel title="Scatter · root distributes distinct chunks"><p className="mb-3 text-[11px] text-[#8299b8]">The root buffer is split by MPI Scatter; each rank receives the value at its rank position.</p><div className="mb-3 flex flex-wrap gap-2">{[10,20,30,40].map((v,i)=><span key={v} className="rounded border border-[#2b4b7a] bg-[#091122] px-3 py-2 font-mono text-xs text-white">{v} → Rank {i}</span>)}</div><div className="grid grid-cols-2 gap-2">{ranks.map(rank=><div key={rank} className={box}><div className="text-[10px] text-[#8299b8]">Rank {rank} receives</div><div className="mt-1 text-lg font-bold text-[#89ceff]">{scatter[rank]??'—'}</div></div>)}</div><div className="mt-3 flex items-center gap-2 text-[11px] text-[#8299b8]">Root → different value per rank <ArrowRight className="h-3 w-3 text-[#89ceff]"/></div></Panel>
      <Panel title="Rank-local calculation and Gather"><p className="mb-3 text-[11px] text-[#8299b8]">Each rank squares its received job work item. MPI Gather then returns rank-ordered results to root.</p><div className="grid grid-cols-2 gap-2">{ranks.map(rank=><div key={rank} className={box}><div className="text-[10px] text-[#8299b8]">Rank {rank} computes</div><div className="mt-1 font-mono text-sm text-white">{scatter[rank]??'—'} → {scatter[rank]===undefined?'—':scatter[rank]*scatter[rank]}</div><div className="mt-2 text-[10px] text-[#8299b8]">Gathered value: <span className="font-semibold text-emerald-300">{gathered[rank]??'—'}</span></div></div>)}</div><div className="mt-3 rounded-lg border border-emerald-900/70 bg-emerald-950/20 p-3"><div className="flex items-center gap-2 text-[10px] uppercase tracking-wide text-emerald-300">Gather · ranks → root <ArrowRight className="h-3 w-3 rotate-180"/></div><div className="mt-1 font-mono text-lg font-bold text-white">{gathered.length?`[${gathered.join(', ')}]`:'Awaiting actual MPI result'}</div></div></Panel>
    </div>
    <Panel title="Actual MPI execution log"><div className="mb-2 flex items-center gap-2 text-[11px] text-[#8299b8]"><Activity className="h-3.5 w-3.5 text-[#89ceff]"/>Events are written from the run and captured MPJ stage markers.</div>{events.length?<div className="space-y-2">{[...events].reverse().map((e:Json)=><div key={e.eventId} className="flex flex-wrap justify-between gap-2 rounded border border-[#1e2f4d] bg-[#091122] px-3 py-2 text-[11px]"><span className="font-semibold text-emerald-200">{e.eventType}</span><span className="text-[#8299b8]">{new Date(e.occurredAt).toLocaleString()}</span></div>)}</div>:<p className="text-xs text-[#8299b8]">No MPI events saved yet.</p>}
      {latest?.summary?.stdout&&<details className="mt-3"><summary className="cursor-pointer text-[11px] text-[#89ceff]">Captured stdout</summary><pre className="mt-2 max-h-64 overflow-auto rounded bg-[#040812] p-3 text-[10px] leading-4 text-emerald-300">{latest.summary.stdout}</pre></details>}
      {latest?.summary?.stderr&&<details className="mt-2"><summary className="cursor-pointer text-[11px] text-amber-200">Captured stderr</summary><pre className="mt-2 max-h-48 overflow-auto rounded bg-[#040812] p-3 text-[10px] leading-4 text-amber-100">{latest.summary.stderr}</pre></details>}
      {latest?.summary?.command&&<p className="mt-3 break-all font-mono text-[10px] text-[#8299b8]">{latest.summary.command}</p>}
    </Panel>
    <div className="flex items-start gap-2 text-[10px] text-[#8299b8]"><CircleHelp className="h-3.5 w-3.5 shrink-0 text-[#89ceff]"/>The root’s broadcast value is identical at all ranks. Scatter sends a different integer to each rank. Gather reverses that direction and collects their computed values at Rank 0.</div>
  </div>;
}
function Metric({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-lg border border-[#1e2f4d] bg-[#091122] p-3"><div className="text-[9px] uppercase tracking-wider text-[#8299b8]">{label}</div><div className="mt-1 truncate text-sm font-bold text-white">{value}</div></div>;}
