import React, { useCallback, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Play, RefreshCw, Shield, Server } from 'lucide-react';

type NodeState = { nodeId:number; role:string; healthy:boolean; leaderId:number; state:string; jobVersion:number|null; jobStatus:string|null };
type Status = { primaryNodeId:number; backupNodeId:number; currentLeaderId:number; primaryHealthy:boolean; failedOver:boolean; jobId:number; jobStatus:string|null; recoveredVersion:number|null; nodes:NodeState[]; observedAt:string };
type Event = { eventId:number; eventType:string; occurredAt:string; nodeId:number|null; jobId:string|null; details:Record<string,unknown> };
const button='inline-flex items-center gap-2 rounded-lg border border-[#2b4b7a] bg-[#182a44] px-3 py-2 text-xs font-semibold text-[#89ceff] transition hover:bg-[#233d64] disabled:cursor-not-allowed disabled:opacity-50';
const input='rounded-lg border border-[#253e65] bg-[#070e1d] px-3 py-2 text-xs text-white outline-none focus:border-[#89ceff]';
async function request<T>(url:string, body?:unknown):Promise<T>{const res=await fetch(url,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json.message||json.error||`${res.status} ${res.statusText}`);return json as T;}

export default function Experiment8Panel(){
  const [jobId,setJobId]=useState('8301');const [version,setVersion]=useState(1);const [status,setStatus]=useState<Status|null>(null);const [events,setEvents]=useState<Event[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const refresh=useCallback(async()=>{const [s,e]=await Promise.all([request<Status>(`/api/experiments/8/status?jobId=${encodeURIComponent(jobId)}`),request<Event[]>('/api/experiments/8/events')]);setStatus(s);setEvents(e);return s;},[jobId]);
  const act=async(label:string,operation:()=>Promise<Status>)=>{setBusy(true);setError('');try{const result=await operation();setStatus(result);setEvents(await request<Event[]>('/api/experiments/8/events'));if(label==='replicate')setVersion(result.recoveredVersion===null?version+1:result.recoveredVersion+1);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  const nodes=status?.nodes??[];const primary=nodes.find(n=>n.nodeId===status?.primaryNodeId);const backup=nodes.find(n=>n.nodeId===status?.backupNodeId);
  const card='rounded-xl border border-[#1e2f4d] bg-[#0e172a] p-4';
  return <div className="space-y-4">
    <section className={card}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-white">Experiment 8 · Fault Tolerance using Primary-Backup Replication</h2><p className="mt-1 text-xs text-[#8299b8]">Node 4 replicates versioned JobRecord updates to Node 3. Node 3 monitors the primary over RMI and takes over when it becomes unavailable.</p></div><button className={button} disabled={busy} onClick={()=>void act('refresh',refresh)}><RefreshCw className="h-3 w-3"/>Refresh status</button></div>
      {error&&<div role="alert" className="mt-3 rounded-lg border border-rose-800 bg-rose-950/40 p-3 text-xs text-rose-200"><AlertTriangle className="mr-2 inline h-4 w-4"/>{error}</div>}
      <div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto_1fr] md:items-center">
        {[{title:'PRIMARY',id:4,node:primary,color:status?.primaryHealthy?'text-emerald-300':'text-rose-300'},{title:'BACKUP',id:3,node:backup,color:status?.failedOver?'text-emerald-300':'text-sky-300'}].map((item,i)=><React.Fragment key={item.title}><div className="rounded-lg border border-[#2b4b7a] bg-[#091122] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-widest text-[#89ceff]">{item.title}</span>{item.node?.healthy?<CheckCircle2 className="h-4 w-4 text-emerald-400"/>:<AlertTriangle className="h-4 w-4 text-rose-400"/>}</div><div className="mt-2 text-lg font-bold text-white">Node {item.id}</div><div className={`mt-1 text-xs font-semibold ${item.color}`}>{item.node?.state??'Awaiting status check'}</div><div className="mt-2 text-[11px] text-[#8299b8]">{item.node?.role??(item.title==='PRIMARY'?'Scheduler leader':'Designated replica')} · leader Node {item.node?.leaderId??'—'}</div></div>{i===0&&<div className="text-center text-xs text-[#89ceff]">{status?.failedOver?'FAILOVER':'JobRecord · synchronous replication'}<div className="mt-1 text-lg">{status?.failedOver?'←':'→'}</div></div>}</React.Fragment>)}
      </div>
      <div className="mt-3 grid gap-2 sm:grid-cols-3"><Metric label="Primary health" value={status?status.primaryHealthy?'AVAILABLE':'FAILED':'—'}/><Metric label="Failover" value={status?status.failedOver?'NODE 3 PROMOTED':'STANDBY':'—'}/><Metric label="Recovered state" value={status?.recoveredVersion===null||status?.recoveredVersion===undefined?'—':`v${status.recoveredVersion} · ${status.jobStatus}`}/></div>
    </section>
    <section className={card}><h3 className="text-sm font-bold text-white">System update demonstration</h3><p className="mt-1 text-xs text-[#8299b8]">Replicate a RUNNING job to the designated backup, make Node 4 unavailable to heartbeat checks and updates, then complete the job through the promoted Node 3.</p><div className="mt-3 flex flex-wrap gap-2"><label className="sr-only" htmlFor="exp8-job">Job ID</label><input id="exp8-job" className={input} type="number" min="1" value={jobId} onChange={e=>setJobId(e.target.value)}/><label className="sr-only" htmlFor="exp8-version">Initial version</label><input id="exp8-version" className={input} aria-label="Initial version" type="number" min="0" value={version} onChange={e=>setVersion(Number(e.target.value))}/><button className={button} disabled={busy} onClick={()=>void act('replicate',()=>request<Status>('/api/experiments/8/replicate',{jobId:Number(jobId),jobType:'MATRIX_MULTIPLICATION',status:'RUNNING',version}))}><Play className="h-3 w-3"/>Synchronize Primary → Backup</button><button className={button} disabled={busy||!status?.recoveredVersion} onClick={()=>void act('failure',()=>request<Status>(`/api/experiments/8/simulate-failure?jobId=${encodeURIComponent(jobId)}`,{}))}><Shield className="h-3 w-3"/>Trigger primary failure</button><button className={button} disabled={busy||!status?.failedOver} onClick={()=>void act('update',()=>request<Status>('/api/experiments/8/update',{jobId:Number(jobId),status:'COMPLETED'}))}><Server className="h-3 w-3"/>Update through promoted Node 3</button></div><div className="mt-3 grid gap-2 text-[11px] text-[#a2b2ca] sm:grid-cols-3"><p><b className="text-white">Fault:</b> Node 4 health check fails and rejects job writes.</p><p><b className="text-white">Recovery:</b> Node 3 detects failure through its scheduled RMI heartbeat and promotes itself.</p><p><b className="text-white">Continued update:</b> Node 3 increments the replicated JobRecord version and commits COMPLETED.</p></div></section>
    <section className={card}><div className="mb-3 flex items-center gap-2"><Activity className="h-4 w-4 text-[#89ceff]"/><h3 className="text-sm font-bold text-white">Persisted failover timeline</h3></div>{events.length? <div className="space-y-2">{[...events].reverse().map(e=><div key={e.eventId} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[#1e2f4d] bg-[#091122] px-3 py-2 text-xs"><span className="font-semibold text-emerald-200">{e.eventType}</span><span className="text-[#8299b8]">{e.nodeId?`Node ${e.nodeId}`:'System'} · Job {e.jobId??'—'} · {new Date(e.occurredAt).toLocaleString()}</span></div>)}</div>:<p className="text-xs text-[#8299b8]">No Experiment 8 events have been recorded yet. Synchronize a job to begin the run.</p>}</section>
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-[#1e2f4d] bg-[#091122] p-3"><div className="text-[9px] uppercase tracking-wider text-[#8299b8]">{label}</div><div className="mt-1 text-sm font-bold text-white">{value}</div></div>;}
