import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Boxes, CheckCircle2, CircleHelp, Clock3, Cpu, Database, ExternalLink, FlaskConical, Gauge, GitBranch, LayoutDashboard, Network, Play, RefreshCw, Server, Shield, Workflow } from 'lucide-react';

type Json = Record<string, any>;
type View = 'dashboard' | 'cluster' | 'jobs' | 'experiments' | 'activity' | `experiment-${number}`;
type FeedItem = { at: string; label: string; detail: string; ok: boolean };
const box = 'rounded-xl border border-[#1e2f4d] bg-[#0e172a] p-4';
const btn = 'inline-flex items-center gap-2 rounded-lg border border-[#2b4b7a] bg-[#182a44] px-3 py-2 text-xs font-semibold text-[#89ceff] transition hover:bg-[#233d64] disabled:cursor-not-allowed disabled:opacity-50';
const input = 'rounded-lg border border-[#253e65] bg-[#070e1d] px-3 py-2 text-xs text-white outline-none focus:border-[#89ceff]';
const experiments = [
  { n: 1, title: 'Client-Server Communication using Java RMI', description: 'Inspect the coordinator, registry and remote node invocation path.', concept: 'Remote Method Invocation', api: true },
  { n: 2, title: 'Multithreading', description: 'Submit a job and inspect its actual execution state through the Java service.', concept: 'Concurrent job execution', api: true },
  { n: 3, title: 'Clock Synchronization', description: 'Read node clocks and invoke Berkeley synchronization on an RMI node.', concept: 'Berkeley algorithm', api: true },
  { n: 4, title: 'Bully and Ring Election', description: 'Run leader election algorithms on the participating Java nodes.', concept: 'Leader election', api: true },
  { n: 5, title: 'Data Consistency and Replication', description: 'Inspect replica versions and invoke synchronous or asynchronous replication.', concept: 'Versioned replication', api: true },
  { n: 6, title: 'Load Balancing', description: 'Read worker load and dispatch a job through the existing LoadBalancer.', concept: 'Distributed scheduling', api: true },
  { n: 7, title: 'MapReduce using Apache Spark', description: 'Run JobRecord aggregation through the Spark Java RDD pipeline.', concept: 'Map · Shuffle · Reduce', api: true },
  { n: 8, title: 'Fault Tolerance / Primary-Backup Replication', description: 'Failure recovery experiment interface is planned.', concept: 'Fault tolerance', api: false },
  { n: 9, title: 'MPI Collective Communication', description: 'MPI collective communication experiment interface is planned.', concept: 'Collective communication', api: false },
  { n: 10, title: 'Parallel Matrix Multiplication using MPI', description: 'Parallel matrix multiplication experiment interface is planned.', concept: 'MPI parallelism', api: false }
];
const pathFor = (view: View) => view === 'experiment-1' || view.startsWith('experiment-') ? `/experiments/${view.split('-')[1]}` : `/${view}`;
function viewForPath(path: string): View { const match = path.match(/^\/experiments\/(\d+)/); if (match) return `experiment-${Math.max(1, Math.min(10, Number(match[1])))}`; return (['/cluster','/jobs','/experiments','/activity'].includes(path) ? path.slice(1) : 'dashboard') as View; }
async function api<T = Json>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || body.error || `${response.status} ${response.statusText}`); return body as T; }
const post = (url: string, body: Json) => api(url, { method: 'POST', body: JSON.stringify(body) });
function Panel({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className={box}><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-white">{title}</h2>{action}</div>{children}</section>; }
function JsonResult({ value }: { value: unknown }) { return <pre className="mt-3 max-h-72 overflow-auto rounded-lg bg-[#040812] p-3 text-[11px] leading-5 text-emerald-300">{JSON.stringify(value, null, 2)}</pre>; }
function Metric({ label, value, icon: Icon }: { label: string; value: React.ReactNode; icon: React.ElementType }) { return <div className={box}><div className="flex items-center justify-between text-[10px] uppercase tracking-wider text-[#8299b8]"><span>{label}</span><Icon className="h-4 w-4 text-[#89ceff]" /></div><div className="mt-2 text-xl font-bold text-white">{value}</div></div>; }

export default function App() {
  const [view, setView] = useState<View>(() => viewForPath(window.location.pathname));
  const [data, setData] = useState<Json | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [feed, setFeed] = useState<FeedItem[]>([]);
  const [result, setResult] = useState<Json | null>(null);
  const [clocks, setClocks] = useState<Json | null>(null);
  const [clusterOffsets, setClusterOffsets] = useState<Record<number, number>>({});
  const [loadData, setLoadData] = useState<Json | null>(null);
  const [rmi, setRmi] = useState<Json | null>(null);
  const [jobId, setJobId] = useState('');
  const [jobType, setJobType] = useState('MAPREDUCE');
  const [nodeId, setNodeId] = useState(1);
  const [version, setVersion] = useState(1);
  const [mode, setMode] = useState('SYNC');
  const [jobStatus, setJobStatus] = useState<Json | null>(null);

  const navigate = useCallback((next: View) => { window.history.pushState({}, '', pathFor(next)); setView(next); setError(''); setResult(null); }, []);
  useEffect(() => { const onPop = () => { setView(viewForPath(window.location.pathname)); setError(''); setResult(null); }; window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  const record = (label: string, value: unknown, ok = true) => setFeed(prev => [{ at: new Date().toLocaleTimeString(), label, detail: ok ? JSON.stringify(value).slice(0, 200) : String(value), ok }, ...prev].slice(0, 40));
  const run = async (label: string, action: () => Promise<Json>) => { const eventLabel = view.startsWith('experiment-') ? `${view}: ${label}` : label; setBusy(true); setError(''); try { const value = await action(); setResult(value); record(eventLabel, value); return value; } catch (e) { const message = e instanceof Error ? e.message : String(e); setError(message); record(eventLabel, message, false); return null; } finally { setBusy(false); } };
  const refresh = useCallback(async () => { setError(''); try { setData(await api('/api/dashboard')); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }, []);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 10000); return () => window.clearInterval(timer); }, [refresh]);
  useEffect(() => { if (view === 'cluster') { void api('/api/nodes').then(setData).catch(e => setError(String(e))); void api('/api/experiments/3/clocks').then((value: Json) => { const readings: Json[] = value.nodes ?? []; const mean = readings.length ? readings.reduce((sum: number, node: Json) => sum + (node.clockTimeEpochMillis ?? 0), 0) / readings.length : 0; setClusterOffsets(Object.fromEntries(readings.map((node: Json) => [node.nodeId, Math.round(node.clockTimeEpochMillis - mean)]))); }).catch(e => setError(String(e))); } }, [view]);
  useEffect(() => { if (view === 'experiment-1') void api('/api/experiments/1/rmi').then(setRmi).catch(e => setError(String(e))); if (view === 'experiment-3') void api('/api/experiments/3/clocks').then(setClocks).catch(e => setError(String(e))); if (view === 'experiment-6') void api('/api/experiments/6/workers/loads').then(setLoadData).catch(e => setError(String(e))); if (view === 'experiment-7') void api('/api/experiments/7').then(setResult).catch(e => setError(String(e))); }, [view]);

  const currentExperiment = view.startsWith('experiment-') ? experiments[Number(view.split('-')[1]) - 1] : undefined;
  const online = data && !Array.isArray(data) ? data.onlineNodes ?? (data.nodes ?? []).filter((n: Json) => n.status === 'ONLINE').length : 0;
  const nodes: Json[] = Array.isArray(data) ? data : data?.nodes ?? [];
  const storedJobs = nodes.reduce((sum: number, n: Json) => sum + (n.jobRecordCount ?? 0), 0);
  const nav = [{ id: 'dashboard' as View, label: 'Dashboard', icon: LayoutDashboard }, { id: 'cluster' as View, label: 'Cluster', icon: Network }, { id: 'jobs' as View, label: 'Jobs', icon: Boxes }, { id: 'experiments' as View, label: 'Experiments', icon: FlaskConical }, { id: 'activity' as View, label: 'Activity', icon: Activity }];
  const backToExperiments = <button className={btn} onClick={() => navigate('experiments')}><ArrowLeft className="h-3.5 w-3.5"/>All experiments</button>;

  return <div className="min-h-screen bg-[#070d18] font-sans text-[#dce2f7] selection:bg-[#89ceff] selection:text-[#00344d]">
    <header className="border-b border-[#1c2b46] bg-[#070e1d] px-5 py-4"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-white"><Network className="h-5 w-5 text-[#89ceff]"/><h1 className="text-lg font-bold">Distributed Computing Lab</h1></div><p className="mt-1 text-xs text-[#8299b8]">Java RMI cluster · Spring Boot adapter · PostgreSQL · Apache Spark</p></div><div className="hidden items-center gap-2 rounded-full border border-emerald-800 bg-emerald-950/40 px-3 py-1 text-[11px] text-emerald-300 sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/>Live integration</div></div></header>
    <nav className="sticky top-0 z-10 border-b border-[#1c2c46] bg-[#091122] px-4"><div className="mx-auto flex max-w-[1500px] gap-1 overflow-x-auto py-1.5">{nav.map(({id,label,icon:Icon}) => <button key={id} onClick={() => navigate(id)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg border px-3.5 py-2 text-xs font-medium ${view === id || (id === 'experiments' && !!currentExperiment) ? 'border-[#2d4972] bg-[#15253d] text-white' : 'border-transparent text-[#8fa6c5] hover:bg-[#0f1b2f] hover:text-white'}`}><Icon className="h-4 w-4 text-[#89ceff]"/>{label}</button>)}</div></nav>
    <main className="mx-auto max-w-[1500px] space-y-5 p-5">
      {error && <div role="alert" className="flex items-start justify-between gap-3 rounded-lg border border-rose-700 bg-rose-950/50 p-3 text-sm text-rose-200"><span>Request failed: {error}</span><button onClick={() => setError('')} aria-label="Dismiss">×</button></div>}
      {view === 'dashboard' && <>
        <PageTitle title="System Dashboard" subtitle="Overall health and current cluster overview. Experiment controls and detailed metrics live on their own pages." action={<button className={btn} onClick={() => void refresh()}><RefreshCw className="h-3.5 w-3.5"/>Refresh</button>}/>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="System health" value={data?.clusterStatus ?? 'Loading'} icon={CheckCircle2}/><Metric label="Active nodes" value={`${online ?? 0} / ${data?.totalNodes ?? 0}`} icon={Server}/><Metric label="Current leader" value={data?.leaderId ? `Node ${data.leaderId}` : '—'} icon={Shield}/><Metric label="Node job records" value={storedJobs} icon={Boxes}/><Metric label="Cluster load" value={nodes.reduce((n: number,x:Json)=>n+(x.currentLoad??0),0)} icon={Gauge}/></div>
        <div className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Panel title="Cluster overview"><NodeTable nodes={nodes.slice(0,4)} compact/></Panel><Panel title="Experiment completion"><div className="space-y-2">{experiments.map(e=><button key={e.n} onClick={()=>navigate(`experiment-${e.n}`)} className="flex w-full items-center justify-between rounded-lg border border-[#1e2f4d] bg-[#091122] px-3 py-2 text-left"><span className="text-xs text-slate-200">Exp {e.n} · {e.title}</span><span className={`text-[10px] ${e.api?'text-emerald-300':'text-amber-300'}`}>{e.api?'IMPLEMENTED':'COMING SOON'}</span></button>)}</div></Panel></div>
        <Panel title="Recent activity"><ActivityList items={feed.slice(0,5)} empty="No actions in this browser session yet." onOpen={()=>navigate('activity')}/></Panel>
      </>}
      {view === 'cluster' && <><PageTitle title="Cluster Infrastructure" subtitle="Live infrastructure state reported by the Java RMI nodes." action={<button className={btn} onClick={()=>{void api('/api/nodes').then(setData).catch(e=>setError(String(e)));void api('/api/experiments/3/clocks').then((value:Json)=>{const readings:Json[]=value.nodes??[];const mean=readings.length?readings.reduce((sum:number,node:Json)=>sum+(node.clockTimeEpochMillis??0),0)/readings.length:0;setClusterOffsets(Object.fromEntries(readings.map((node:Json)=>[node.nodeId,Math.round(node.clockTimeEpochMillis-mean)])));}).catch(e=>setError(String(e)));}}><RefreshCw className="h-3.5 w-3.5"/>Refresh cluster</button>}/><div className="grid gap-3 sm:grid-cols-3"><Metric label="Nodes online" value={`${nodes.filter(n=>n.status==='ONLINE').length} / ${nodes.length}`} icon={Server}/><Metric label="Leader" value={nodes.find(n=>n.id===nodes[0]?.leaderId)?.leaderId ? `Node ${nodes[0].leaderId}` : '—'} icon={Shield}/><Metric label="Current load" value={nodes.reduce((n,x)=>n+(x.currentLoad??0),0)} icon={Gauge}/></div><Panel title="Node health, RMI endpoint, load and clock offset"><NodeTable nodes={nodes} clockOffsets={clusterOffsets}/></Panel><p className="text-[11px] text-[#8299b8]">Clock offsets are calculated from the live RMI readings relative to their observed mean. Status timestamps are exposed; heartbeat intervals are not.</p></>}
      {view === 'jobs' && <JobsPage run={run} busy={busy} jobId={jobId} setJobId={setJobId} jobType={jobType} setJobType={setJobType} jobStatus={jobStatus} setJobStatus={setJobStatus} result={result} nodes={nodes}/>}
      {view === 'experiments' && <><PageTitle title="Experiments" subtitle="Choose a lab to view its objective, implementation status and dedicated controls."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{experiments.map(e=><article key={e.n} className={`${box} flex flex-col`}><div className="flex items-start justify-between gap-3"><span className="rounded-md border border-[#2d4972] bg-[#15253d] px-2 py-1 font-mono text-[10px] text-[#89ceff]">EXPERIMENT {String(e.n).padStart(2,'0')}</span><span className={`rounded-full border px-2 py-1 text-[9px] font-bold tracking-wide ${e.api?'border-emerald-800 bg-emerald-950/60 text-emerald-300':'border-amber-800 bg-amber-950/40 text-amber-200'}`}>{e.api?'IMPLEMENTED':'COMING SOON'}</span></div><h2 className="mt-4 text-base font-bold text-white">{e.title}</h2><p className="mt-2 min-h-10 text-xs leading-5 text-[#9aacc7]">{e.description}</p><div className="mt-4 flex items-center justify-between border-t border-[#1e2f4d] pt-3"><span className="text-[10px] text-[#8299b8]">Concept: {e.concept}</span><button className={btn} onClick={()=>navigate(`experiment-${e.n}`)}>Open experiment<ArrowRight className="h-3 w-3"/></button></div></article>)}</div></>}
      {view === 'activity' && <><PageTitle title="Activity" subtitle="API actions recorded during this browser session. This feed is session-scoped; persisted event history is not exposed by a frontend API."/><Panel title={`Session events · ${feed.length}`}><ActivityList items={feed} empty="No API actions recorded in this session. Open an experiment and run an operation to see its actual response here."/></Panel></>}
      {currentExperiment && <ExperimentPage experiment={currentExperiment} back={backToExperiments} busy={busy} run={run} result={result} setResult={setResult} rmi={rmi} clocks={clocks} setClocks={setClocks} loadData={loadData} setLoadData={setLoadData} nodeId={nodeId} setNodeId={setNodeId} jobId={jobId} setJobId={setJobId} jobType={jobType} setJobType={setJobType} version={version} setVersion={setVersion} mode={mode} setMode={setMode} feed={feed}/>}
    </main>
  </div>;
}

function PageTitle({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-bold text-white">{title}</h1><p className="mt-1 text-xs text-[#8299b8]">{subtitle}</p></div>{action}</div>; }
function NodeTable({nodes,compact=false,clockOffsets={}}:{nodes:Json[];compact?:boolean;clockOffsets?:Record<number,number>}) { return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase tracking-wide text-[#8299b8]"><tr>{['Node','RMI endpoint','Status','Leader','Load',...(compact?[]:['Clock offset','Job records','Observed'])].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{nodes.map(n=><tr key={n.id} className="border-t border-[#1e2f4d]"><td className="p-2 font-semibold text-white">Node {n.id}</td><td className="p-2 font-mono text-[#a8bad4]">{n.host}:{n.port}</td><td className="p-2"><span className={n.status==='ONLINE'?'text-emerald-300':'text-rose-300'}>{n.status}</span></td><td className="p-2">{n.leaderId===n.id?'Leader':`Node ${n.leaderId??'—'}`}</td><td className="p-2">{n.currentLoad??'—'}</td>{!compact&&<><td className="p-2">{clockOffsets[n.id]===undefined?'—':`${clockOffsets[n.id]>0?'+':''}${clockOffsets[n.id]} ms`}</td><td className="p-2">{n.jobRecordCount??'—'}</td><td className="p-2">{n.observedAt?new Date(n.observedAt).toLocaleTimeString():'—'}</td></>}</tr>)}</tbody></table>{nodes.length===0&&<p className="p-3 text-xs text-[#8299b8]">Waiting for node data…</p>}</div>; }
function ActivityList({items,empty,onOpen}:{items:FeedItem[];empty:string;onOpen?:()=>void}) { return items.length?<div className="divide-y divide-[#1e2f4d]">{items.map((i,n)=><div key={`${i.at}-${n}`} className="flex gap-3 py-2 text-xs"><span className="font-mono text-[#8299b8]">{i.at}</span><span className={i.ok?'text-emerald-300':'text-rose-300'}>{i.ok?'SUCCESS':'FAILED'}</span><span className="text-slate-200">{i.label}</span><span className="truncate text-[#8299b8]">{i.detail}</span></div>)}</div>:<div className="text-xs text-[#8299b8]">{empty}{onOpen&&<button className="ml-2 text-[#89ceff]" onClick={onOpen}>View activity</button>}</div>; }

function JobsPage({run,busy,jobId,setJobId,jobType,setJobType,jobStatus,setJobStatus,result,nodes}:{run:(label:string,action:()=>Promise<Json>)=>Promise<Json|null>;busy:boolean;jobId:string;setJobId:(v:string)=>void;jobType:string;setJobType:(v:string)=>void;jobStatus:Json|null;setJobStatus:(v:Json|null)=>void;result:Json|null;nodes:Json[]}) { const [newId,setNewId]=useState('9001'); const [recent,setRecent]=useState<Json[]>([]); return <><PageTitle title="Jobs" subtitle="Submit or inspect actual jobs through the existing Spring Boot and Java RMI integration."/><div className="grid gap-4 xl:grid-cols-2"><Panel title="Submit job · Experiment 2"><p className="mb-3 text-xs text-[#8299b8]">The backend submission route invokes the existing coordinator. Thread-pool internals are only shown if returned by that implementation.</p><div className="flex flex-wrap gap-2"><input className={input} aria-label="New job ID" value={newId} onChange={e=>setNewId(e.target.value)} placeholder="Job ID"/><input className={input} aria-label="Job type" value={jobType} onChange={e=>setJobType(e.target.value)}/><button className={btn} disabled={busy} onClick={()=>void run('Job submitted',async()=>{const value=await post('/api/experiments/2/jobs',{jobId:Number(newId),jobType,status:'QUEUED',version:1});setRecent(prev=>[value,...prev].slice(0,10));return value;})}><Play className="h-3 w-3"/>Submit through RMI</button></div>{recent.length>0&&<div className="mt-4"><h3 className="text-xs font-semibold text-white">Submitted in this session</h3>{recent.map((j,i)=><div key={i} className="mt-2 rounded border border-[#1e2f4d] p-2 text-xs">{JSON.stringify(j)}</div>)}</div>}</Panel><Panel title="Job lifecycle lookup"><p className="mb-3 text-xs text-[#8299b8]">Look up the status of a submitted job by ID.</p><div className="flex flex-wrap gap-2"><input className={input} aria-label="Lookup job ID" value={jobId} onChange={e=>setJobId(e.target.value)} placeholder="Job ID"/><button className={btn} disabled={busy||!jobId} onClick={()=>void run('Job status lookup',async()=>{const v=await api(`/api/experiments/2/jobs/${encodeURIComponent(jobId)}`);setJobStatus(v);return v;})}>Get job status</button></div>{jobStatus&&<JsonResult value={jobStatus}/ >}</Panel></div><Panel title="Current runtime node records"><p className="mb-3 text-[11px] text-[#8299b8]">Node records are not a global job history: replicas may appear on multiple nodes. No global list endpoint is currently exposed.</p><NodeTable nodes={nodes}/></Panel>{result&&<Panel title="Latest operation result"><JsonResult value={result}/></Panel>}</>; }

function ExperimentPage({experiment:e,back,busy,run,result,setResult,rmi,clocks,setClocks,loadData,setLoadData,nodeId,setNodeId,jobId,setJobId,jobType,setJobType,version,setVersion,mode,setMode,feed}:{experiment:typeof experiments[number];back:React.ReactNode;busy:boolean;run:(label:string,action:()=>Promise<Json>)=>Promise<Json|null>;result:Json|null;setResult:(v:Json|null)=>void;rmi:Json|null;clocks:Json|null;setClocks:(v:Json|null)=>void;loadData:Json|null;setLoadData:(v:Json|null)=>void;nodeId:number;setNodeId:(v:number)=>void;jobId:string;setJobId:(v:string)=>void;jobType:string;setJobType:(v:string)=>void;version:number;setVersion:(v:number)=>void;mode:string;setMode:(v:string)=>void;feed:FeedItem[]}) {
  const nodes:Json[]=clocks?.nodes??[]; const avg=nodes.length?nodes.reduce((s:number,n:Json)=>s+(n.clockTimeEpochMillis??0),0)/nodes.length:0;
  const loads:Json[]=loadData?.workers??[];
  const experimentFeed=feed.filter(item=>item.label.startsWith(`experiment-${e.n}:`));
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3">{back}<div className="mr-auto"><div className="text-[10px] font-mono tracking-widest text-[#89ceff]">EXPERIMENT {String(e.n).padStart(2,'0')} · {e.api?'LIVE BACKEND':'PLACEHOLDER'}</div><h1 className="mt-1 text-xl font-bold text-white">{e.title}</h1><p className="mt-1 text-xs text-[#8299b8]">{e.description}</p></div><span className={`rounded-full border px-3 py-1 text-[10px] font-bold ${e.api?'border-emerald-800 bg-emerald-950/50 text-emerald-300':'border-amber-800 bg-amber-950/50 text-amber-200'}`}>{e.api?'IMPLEMENTED':'BACKEND IMPLEMENTATION PENDING'}</span></div>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Aim / concept" value={e.concept} icon={CircleHelp}/><Metric label="Nodes involved" value="Java RMI nodes" icon={Server}/><Metric label="Current execution" value={busy?'RUNNING':result?'RESULT AVAILABLE':'READY'} icon={Activity}/></div>
    <div className="grid gap-4 xl:grid-cols-[1.35fr_1fr]"><div className="space-y-4">
      {!e.api&&<Panel title="Placeholder · Backend implementation pending"><p className="text-sm font-semibold text-amber-200">This experiment has no live backend integration yet.</p><p className="mt-2 text-xs text-[#9aacc7]">The page is reserved for the {e.concept} lab. No runtime state, controls, or results are fabricated.</p></Panel>}
      {e.n===1&&<><Panel title="Client → RMI Registry → Coordinator → NodeService"><div className="grid gap-2 sm:grid-cols-4">{['Client','RMI Registry','Coordinator','NodeService'].map((x,i)=><div key={x} className="rounded-lg border border-[#2b4b7a] bg-[#091122] p-3 text-center text-xs text-white">{x}{i<3&&<div className="mt-2 text-[#89ceff]">{i===0?'RMI lookup':i===1?'remote call':'response'}</div>}</div>)}</div><p className="mt-3 text-[11px] text-[#8299b8]">Client view is this frontend; Spring Boot adapts HTTP calls to the existing coordinator and node services.</p></Panel><Panel title="Registry and node reachability" action={<button className={btn} onClick={()=>void run('RMI reachability check',()=>api('/api/experiments/1/rmi'))}><RefreshCw className="h-3 w-3"/>Probe RMI</button>}>{rmi&&<><div className="text-xs text-slate-200">Coordinator: {rmi.coordinator?.host}:{rmi.coordinator?.port} · {rmi.coordinator?.reachable?'reachable':'unavailable'}</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{(rmi.nodes??[]).map((n:Json)=><div key={n.nodeId} className="rounded-lg border border-[#1e2f4d] p-3 text-xs">Node {n.nodeId} · {n.host}:{n.port} · {n.reachable?'reachable':'unavailable'}</div>)}</div></>}</Panel></>}
      {e.n===2&&<Panel title="Job queue → worker thread pool"><p className="mb-3 text-xs text-[#8299b8]">Submit a job using the existing endpoint, then inspect the returned execution state. Thread count and active task metrics are shown only if supplied by the Java implementation.</p><div className="flex flex-wrap gap-2"><input className={input} aria-label="Job ID" value={jobId} onChange={x=>setJobId(x.target.value)} placeholder="Job ID"/><input className={input} aria-label="Job type" value={jobType} onChange={x=>setJobType(x.target.value)}/><button className={btn} disabled={busy} onClick={()=>void run('Experiment 2 job submission',()=>{const id=Number(jobId||'9002');setJobId(String(id));return post('/api/experiments/2/jobs',{jobId:id,jobType,status:'QUEUED',version:1});})}><Play className="h-3 w-3"/>Submit concurrent job</button><button className={btn} disabled={busy||!jobId} onClick={()=>void run('Experiment 2 execution state',()=>api(`/api/experiments/2/jobs/${encodeURIComponent(jobId)}`))}>Refresh job state</button></div><div className="mt-5 grid grid-cols-4 gap-2">{['Job Queue','Thread Pool','Worker Thread','Job Result'].map((x,i)=><div key={x} className="rounded-lg border border-[#1e2f4d] bg-[#091122] p-3 text-center text-xs"><div className="text-[#89ceff]">{i<3?'↓':'✓'}</div><div className="mt-1 text-white">{x}</div></div>)}</div></Panel>}
      {e.n===3&&<><Panel title="Berkeley clock readings" action={<button className={btn} disabled={busy} onClick={()=>void run('Read RMI node clocks',async()=>{const v=await api('/api/experiments/3/clocks');setClocks(v);return v;})}><RefreshCw className="h-3 w-3"/>Read clocks</button>}><div className="grid gap-2 sm:grid-cols-2">{nodes.map((n:Json)=><div key={n.nodeId} className="rounded-lg border border-[#1e2f4d] bg-[#091122] p-3"><div className="flex justify-between text-xs"><b className="text-white">Node {n.nodeId}</b><span className={n.reachable?'text-emerald-300':'text-rose-300'}>{n.reachable?'reachable':'offline'}</span></div><div className="mt-2 font-mono text-sm text-[#89ceff]">{n.clockTime??'—'}</div><div className="mt-1 text-[11px] text-[#8299b8]">Offset from observed average: {avg?`${Math.round(n.clockTimeEpochMillis-avg)} ms`:'—'}</div></div>)}</div></Panel><Panel title="Berkeley synchronization"><p className="mb-3 text-xs text-[#8299b8]">The synchronization operation is sent to the selected Java RMI node.</p><div className="flex gap-2"><select className={input} value={nodeId} onChange={x=>setNodeId(Number(x.target.value))}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select><button className={btn} disabled={busy} onClick={()=>void run('Berkeley synchronization',async()=>{const v=await post('/api/experiments/3/synchronize',{nodeId});const latest=await api('/api/experiments/3/clocks');setClocks(latest);return v;})}><Clock3 className="h-3 w-3"/>Synchronize clocks</button></div></Panel></>}
      {e.n===4&&<Panel title="Election operation · Java RMI"><p className="mb-3 text-xs text-[#8299b8]">Choose the initiator and run one election algorithm at a time. The displayed timeline is the actual endpoint response.</p><div className="flex flex-wrap items-center gap-2"><label className="text-xs text-[#8299b8]">Initiator</label><select className={input} value={nodeId} onChange={x=>setNodeId(Number(x.target.value))}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select>{(['bully','ring'] as const).map(a=><button key={a} className={btn} disabled={busy} onClick={()=>void run(`${a} election`,()=>post(`/api/experiments/4/elections/${a}`,{nodeId}))}><Play className="h-3 w-3"/>Run {a} election</button>)}</div><div className="mt-5 flex items-center justify-between gap-2">{[1,2,3,4].map(n=><div key={n} className="rounded-lg border border-[#1e2f4d] bg-[#091122] px-4 py-3 text-xs">Node {n}</div>)}</div></Panel>}
      {e.n===5&&<Panel title="JobRecord replication and versions"><p className="mb-3 text-xs text-[#8299b8]">Replicate to the actual RMI nodes and inspect the returned replica/version state.</p><div className="flex flex-wrap gap-2"><input className={input} aria-label="Job ID" type="number" value={jobId||'7001'} onChange={x=>setJobId(x.target.value)}/><input className={input} aria-label="Version" type="number" value={version} onChange={x=>setVersion(Number(x.target.value))}/><select className={input} value={mode} onChange={x=>setMode(x.target.value)}><option value="SYNC">Synchronous</option><option value="ASYNC">Asynchronous</option></select><button className={btn} disabled={busy} onClick={()=>void run('Replicate JobRecord',()=>post('/api/experiments/5/replication',{jobId:Number(jobId||7001),jobType,status:'RUNNING',version,primaryNodeId:nodeId,mode}))}>Replicate</button><button className={btn} disabled={busy} onClick={()=>void run('Read replica versions',()=>api(`/api/experiments/5/jobs/${jobId||7001}/replicas`))}>Read replicas</button></div><div className="mt-4 rounded-lg border border-amber-800/70 bg-amber-950/20 p-3 text-xs text-amber-100">Stale-version check: submitting a version lower than the current JobRecord should be rejected by the replication implementation. The result below reports the actual response.</div></Panel>}
      {e.n===6&&<><Panel title="Worker loads · Java LoadBalancer"><div className="grid gap-2 sm:grid-cols-3">{loads.map((w:Json)=><div key={w.nodeId} className="rounded-lg border border-[#1e2f4d] p-3"><div className="flex justify-between text-xs"><b className="text-white">Node {w.nodeId}</b><span className="text-[#8299b8]">{w.reachable?'available':'offline'}</span></div><div className="mt-2 text-2xl font-bold text-[#89ceff]">{w.currentLoad??'—'}<span className="ml-1 text-[10px] font-normal text-[#8299b8]">current load</span></div></div>)}</div><button className={`${btn} mt-3`} disabled={busy} onClick={()=>void run('Refresh worker loads',async()=>{const v=await api('/api/experiments/6/workers/loads');setLoadData(v);return v;})}><RefreshCw className="h-3 w-3"/>Refresh loads</button></Panel><Panel title="Route incoming job"><div className="mb-4 flex items-center justify-between gap-1 text-center text-[10px] sm:text-xs">{['Incoming Job','Compare worker loads','LoadBalancer selects node','NodeService receives job'].map((x,i)=><React.Fragment key={x}><span className="rounded border border-[#1e2f4d] bg-[#091122] p-2">{x}</span>{i<3&&<ArrowRight className="h-4 w-4 shrink-0 text-[#89ceff]"/>}</React.Fragment>)}</div><div className="flex flex-wrap gap-2"><input className={input} aria-label="Job ID" type="number" value={jobId||'7002'} onChange={x=>setJobId(x.target.value)}/><input className={input} aria-label="Job type" value={jobType} onChange={x=>setJobType(x.target.value)}/><button className={btn} disabled={busy} onClick={()=>void run('LoadBalancer dispatch',async()=>{const v=await post('/api/experiments/6/jobs/dispatch',{jobId:Number(jobId||7002),jobType,status:'QUEUED',version:0});setLoadData(await api('/api/experiments/6/workers/loads'));return v;})}><Play className="h-3 w-3"/>Dispatch through LoadBalancer</button></div></Panel></>}
      {e.n===7&&<><Panel title="Spark Java RDD · JobRecord[] → results"><div className="grid grid-cols-5 items-center gap-2 text-center">{['Input records','MAP\n(JobType, 1)','SHUFFLE','REDUCE\nsum','Results'].map((stage,i)=><div key={stage} className="rounded-lg border border-[#2b4b7a] bg-[#091122] p-3 text-[11px] font-semibold text-white"><div className="text-[#89ceff]">{i===0?'▤':i===4?'Σ':i===2?'⇄':'↓'}</div><div className="mt-1 whitespace-pre-line">{stage}</div></div>)}</div></Panel><Panel title="Run Apache Spark MapReduce"><p className="mb-3 text-xs text-[#8299b8]">Executes Spark using the existing request dataset contract. Failure is shown directly and is never labeled as a successful run.</p><div className="flex flex-wrap gap-2"><button className={btn} disabled={busy} onClick={()=>void run('Spark MapReduce run',()=>post('/api/experiments/7/run',{jobRecords:['MAPREDUCE','SPARK_RDD','MAPREDUCE','MPI_COLLECTIVE','SPARK_RDD','MAPREDUCE','MPI_COLLECTIVE','SPARK_RDD'].map((jobType,i)=>({jobId:8100+i,jobType,status:'COMPLETED',version:1})),partitions:2}))}><Play className="h-3 w-3"/>Run Spark MapReduce</button><button className={btn} disabled={busy} onClick={()=>void run('Load latest Spark run',()=>api('/api/experiments/7'))}>Load persisted latest run</button></div></Panel></>}
    </div><div className="space-y-4"><Panel title="Aim · Algorithm · Nodes"><div className="space-y-3 text-xs"><div><b className="text-white">Aim</b><p className="mt-1 text-[#9aacc7]">{e.description}</p></div><div><b className="text-white">Algorithm / concept</b><p className="mt-1 text-[#9aacc7]">{e.concept}</p></div><div><b className="text-white">Runtime</b><p className="mt-1 text-[#9aacc7]">{e.api?'Operations call the actual existing backend.':'Backend implementation pending; no runtime calls are made.'}</p></div></div></Panel>{e.api&&<Panel title={e.n===3?'Clock readings':e.n===6?'Worker load state':e.n===1?'RMI reachability':e.n===7?'Latest persisted run':'Actual operation result'}>{(e.n===3?clocks:e.n===6?loadData:e.n===1?rmi:result)?<JsonResult value={e.n===3?clocks:e.n===6?loadData:e.n===1?rmi:result}/>:<p className="text-xs text-[#8299b8]">Run or refresh an operation to view its actual response.</p>}</Panel>}<Panel title="Experiment event log"><ActivityList items={experimentFeed} empty="Run an operation to record its actual response in this session."/></Panel></div></div>
  </div>;
}
