-- Node rows are last-known observations; active reachability is queried from RMI.
CREATE TABLE nodes (
    node_id INTEGER PRIMARY KEY,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
    reachable BOOLEAN NOT NULL,
    leader_id INTEGER,
    current_load INTEGER,
    job_count INTEGER,
    observed_at TIMESTAMPTZ NOT NULL,
    last_error TEXT
);

CREATE TABLE jobs (
    job_id VARCHAR(128) PRIMARY KEY,
    experiment_run_id BIGINT,
    status VARCHAR(32) NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    submitted_node_id INTEGER REFERENCES nodes(node_id),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE job_replicas (
    job_id VARCHAR(128) NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    node_id INTEGER NOT NULL REFERENCES nodes(node_id),
    replica_role VARCHAR(32) NOT NULL DEFAULT 'REPLICA',
    status VARCHAR(32) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(job_id, node_id)
);

CREATE TABLE experiment_runs (
    experiment_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_number INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    error TEXT
);

ALTER TABLE jobs ADD CONSTRAINT jobs_experiment_run_fk
    FOREIGN KEY (experiment_run_id) REFERENCES experiment_runs(experiment_run_id);

CREATE TABLE system_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(80) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    node_id INTEGER REFERENCES nodes(node_id),
    job_id VARCHAR(128),
    details JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE mapreduce_runs (
    mapreduce_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(128) REFERENCES jobs(job_id),
    status VARCHAR(32) NOT NULL,
    input_description JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    error TEXT
);

CREATE TABLE mapreduce_results (
    mapreduce_run_id BIGINT NOT NULL REFERENCES mapreduce_runs(mapreduce_run_id) ON DELETE CASCADE,
    result_key TEXT NOT NULL,
    result_value JSONB NOT NULL,
    produced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(mapreduce_run_id, result_key)
);

CREATE INDEX jobs_status_submitted_idx ON jobs(status, submitted_at DESC);
CREATE INDEX job_replicas_node_idx ON job_replicas(node_id, status);
CREATE INDEX experiment_runs_started_idx ON experiment_runs(started_at DESC);
CREATE INDEX system_events_occurred_idx ON system_events(occurred_at DESC);
CREATE INDEX mapreduce_runs_started_idx ON mapreduce_runs(started_at DESC);
